version: "3.8"

services:
  freac:
    image: jlesage/freac
    container_name: freac
    ports:
      - "5800:5800"
    volumes:
      - /home/banditecho/freac-config:/config
      - /mnt/nas-media/Media/Audio-ripped:/output
    devices:
      - /dev/sr1:/dev/sr0
    restart: unless-stopped